### PR TITLE
Optionally emit SV lengths

### LINKED ISSUE #503: Allow the optional emission of sv length of evidence
After calling sv's the vcf record include the median sv length found in the reads that support the SV in question. It is sometimes useful to know the various SV-lengths that went into a particular SV (for debugging purposes and for fine-tuning the parameters controling the clustering of evidence onto individual SVs, for example)

It would be nice to be able to (optionally) emit the individual lengths of the SV's as seen in the evidence (reads). This could be written to the VCF as a list of integers in a new tag (for example SVLENGTHS)

As I've already written the code to do this, I'll be submitting a PR shortly, however, I'm happy do discuss the merits of the idea here, and the details of the implementation on the PR.  

Thanks!

### PR DESCRIPTION
**Pull request by yfarjoun**
closes #503 

This PR adds a commandline argument that emits the lengths of the SVs found on the reads into the VCF record that contains the resulting SV. The argument is suppressed (not showing in the "help") and is prefixed with `dev-` to indicate that it's a development/debugging option.

The only change to the output is the (currently non-optional) addition of the `SVLENGTHS` header line in the VCF. However, I'm happy to make this also optional. otherwise, the algorithm and output are unchanged unless `--dev-emit-sv-lengths` is provided on the command-line.

### CODE REVIEW

**Comment by yfarjoun** [comment]
I'd love to know what needs to be done to get some traction on this PR. It doesn't change the default behaviour, but it allows users to better understand the distribution of svlengths that the call have and thus perform better clustering and other downstream analyses. 

Please do consider these changes and let me know if there's anything I can do to make it easier for the maintainers.

**Comment by fritzsedlazeck** [comment]
Thanks @hermannromanek could you take a look?

**Comment by yfarjoun** [comment]
Hi, I know it's not easy to find time to maintain a OSS repo. If there's anything I can do to make it easier to review my PR, Please let me know!

**Comment by fritzsedlazeck** [comment]
Dear @yfarjoun 
Thanks. we are working on this. This is on me.. i wanted a development github that is private and this public facing github. so now Herman needs to merge before the new release and this is unfortunately the way these things are getting incorporated. 
Hope that kinda makes sense but we wanted to have a code environment that we can explore things with :). 
Thanks
Fritz

**Comment by yfarjoun** [comment]
Thanks for the explanation @fritzsedlazeck, that makes total sense! I will not mis-take the silence for lack of response anymore 😄

**Comment by yfarjoun** [comment]
🎉

**Comment by yfarjoun** [comment]
Thanks!! 🥳

**Comment by hermannromanek** [comment]
Preparing release 2.5 right now :)

**Pull request merged**
